* help fill out tax forms
  minimum version shown here is just for federal form 1040

  fill out questions once, it will do the calculations and fill out
  the official pdf from irs.gov.

  live right now at https://tax.each.do/

* tech stack
** backend
*** apache2
**** reverse proxy for backend, and front
*** systemd manages postgres
*** letsencrypt for ssl
*** pipenv
*** postgres for db
*** flask
*** sqlalchemy
*** talisman for https
*** gunicorn for http requests
*** factoryboy for generating fake data for tests
*** pytest
** frontend
*** apache2
**** reverse proxy for frontend
*** systemd manages pm2
*** react+vite: fast html update via virtual dom and batched dispatch
*** redux toolkit state management
*** axios http request session management
*** pdf-lib fills out the pdf for download

* tax project monorepo

this repository contains synchronized versions of the tax app's
frontend and backend.

** repository structure

#+begin_example
  tax/
  ├── front/  # frontend repository
  └── back/   # backend repository
#+end_example

** version synchronization

the frontend and backend repositories are maintained as git
submodules. version tags are used to mark compatible releases between
the two components.

*** version scheme

each parent repository commit indicates verified compatible versions.

** development

*** initial setup

#+begin_src bash
  git clone --recursive <tax-url>
#+end_src

*** making changes

1. make changes in respective submodules
2. test compatibility between frontend and backend
3. update submodule references in parent repository

#+begin_src bash
  # modify front and/or back.
  #  showing front here
  cd front
  git fetch
  # edit files
  git add <edited-files>
  git commit -m "edit files"
  git push
  cd ..
  # confirm front and back still work together
  git add front
  git commit -m "made front better"
#+end_src

** deployment

1. get the latest version of the top repo
2. checkout all submodules to what the parent repo says they should be

*** new deployment

get the code

#+begin_src bash
  git clone --recursive <tax-url>
#+end_src

*** update an existing deployment

get the latest version of the parent repo, and the submodules at the
versions specified by the parent repo.

#+begin_src bash
  cd tax
  git pull
  git submodule update --init --recursive
#+end_src

*** deploy backend

see the readme in the backend

*** deploy frontend

see the readme in the frontend
